export const siteConfig = {
	name: "nova-svelte",
	url: "https://nova-svelte.com",
	ogImage: {
		url: "https://nova-svelte.com/opengraph-image.png",
		width: "1200",
		height: "630",
	},
	description:
		"A set of beautifully-designed, accessible components and a code distribution platform. Open Source. Open Code.",
	keywords: [
		"shadcn-svelte",
		"svelte components",
		"svelte ui library",
		"svelte design system",
		"tailwindcss components",
		"headless ui svelte",
		"accessible svelte components",
		"copy paste components",
		"svelte component library",
		"sveltekit components",
		"svelte 5 components",
		"svelte runes",
		"bits-ui",
		"radix svelte",
		"shadcn svelte",
		"free ui components",
		"open source components",
		"modern ui svelte",
		"typescript svelte components",
		"responsive components",
		"dark mode components",
		"form components svelte",
		"dashboard components",
		"chart components svelte",
		"svelte chart components",
	],
	links: {
		x: "https://x.com/_LilShad",
		github: "https://github.com/PandaShad/arcana-ui",
	},
};